var searchData=
[
  ['a_20function_0',['Fake a return value from a function',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md35',1,'']]],
  ['a_20function_20pointer_20parameter_1',['Fake a function with a function pointer parameter',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md37',1,'']]],
  ['a_20function_20was_20called_20once_2',['Test that a function was called once',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md31',1,'']]],
  ['a_20function_20was_20not_20called_3',['Test that a function was NOT called',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md32',1,'']]],
  ['a_20function_20with_20a_20function_20pointer_20parameter_4',['Fake a function with a function pointer parameter',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md37',1,'']]],
  ['a_20function_20with_20a_20value_20returned_20by_20reference_5',['Fake a function with a value returned by reference',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md36',1,'']]],
  ['a_20particular_20sequence_6',['Test that calls are made in a particular sequence',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md34',1,'']]],
  ['a_20return_20value_20from_20a_20function_7',['Fake a return value from a function',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md35',1,'']]],
  ['a_20single_20function_20was_20called_20with_20the_20correct_20argument_8',['Test that a single function was called with the correct argument',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md33',1,'']]],
  ['a_20value_20returned_20by_20reference_9',['Fake a function with a value returned by reference',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md36',1,'']]],
  ['abortframe_10',['AbortFrame',['../struct_u_n_i_t_y___s_t_o_r_a_g_e___t.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'UNITY_STORAGE_T::AbortFrame'],['../mock__booster_state_machine_8c.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'AbortFrame:&#160;mock_boosterStateMachine.c'],['../mock__current_sensors_config_update_8c.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'AbortFrame:&#160;mock_currentSensorsConfigUpdate.c'],['../mock__current_sensorsread_channel_8c.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'AbortFrame:&#160;mock_currentSensorsreadChannel.c'],['../mock__current_sensors_update_database_8c.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'AbortFrame:&#160;mock_currentSensorsUpdateDatabase.c'],['../mock__laser_data_8c.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'AbortFrame:&#160;mock_laserData.c'],['../mock__lna_state_machine_8c.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'AbortFrame:&#160;mock_lnaStateMachine.c'],['../mock__power_read_channel_8c.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'AbortFrame:&#160;mock_powerReadChannel.c'],['../mock__power_sensors_config_update_8c.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'AbortFrame:&#160;mock_powerSensorsConfigUpdate.c'],['../mock__power_sensors_update_database_8c.html#add1ad6305e99da2ddf841e32dfbd8bd5',1,'AbortFrame:&#160;mock_powerSensorsUpdateDatabase.c']]],
  ['are_20made_20in_20a_20particular_20sequence_11',['Test that calls are made in a particular sequence',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md34',1,'']]],
  ['argument_12',['Test that a single function was called with the correct argument',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/README.md#autotoc_md33',1,'']]],
  ['artifacts_13',['Artifacts',['../C:/myWorks/mynaric/Application/embedded/mynaricApp_Embedded/mynaricCondor/mynaricCondor/src/ASF/sam/components/Sensors/UnitTestFramework/vendor/ceedling/plugins/dependencies/README.md#autotoc_md13',1,'']]]
];
